[workspace]
name = "telight-server"
description = "Python environments for the Telight-EDIH-IT4I project, segmentation server"
authors = ["Vladimír Ulman <vladimir.ulman@vsb.cz>"]

license = "BSD-3-Clause"
license-file = "../../LICENSE"
readme = "../../README.md"

platforms = ["linux-64", "win-64"]
channels = ["conda-forge", "pytorch"]
version = "0.1.3"

[environments]
cpu = ["cpu"]
default = ["gpu"]

[feature.cpu.system-requirements]
# empty

[feature.gpu.system-requirements]
cuda = "12.6"

[feature.cpu.dependencies]
pytorch = "2.6.*"

[feature.gpu.dependencies]
cuda-version = "==12.6"
pytorch-gpu = "2.6.*"

[dependencies]
torchvision = ">=0.21.0,<0.22"
scikit-image = ">=0.24.0,<0.25"
scikit-learn = ">=1.5.2,<2"
tifffile = ">=2024.6.18,<2025"
imagecodecs = ">=2024.9.22,<2025"
tqdm = ">=4.67.1,<5"
pandas = ">=2.2.3,<3"
albumentations = ">=1.4.20,<2"

# for full StarDist
#tensorflow = "==2.17.0"

# for InstanSeg
seaborn = ">=0.13.2,<0.14"
monai = ">=1.4.0,<2"
imageio = ">=2.11.0,<2.28.0"
edt = ">=2.4.1,<3"
numba = ">=0.61.2,<0.62"
llvmlite = ">=0.44.0,<0.45"

# for server
fastapi = ">=0.115.12,<0.116"
cryptography = ">=45.0.3,<46"

[pypi-dependencies]
cellpose = ">=4.0.0"
stardist = ">=0.9.1, <0.10"
instanseg-torch = { path = "/mnt/proj2/dd-24-22/networks/instanseg", editable = true }
embedseg = { path = "/mnt/proj2/dd-24-22/networks/EmbedSeg", editable = true }
#embedseg = ">=0.2.5" also works

## # and then add the EmbedSeg itself
## git clone https://github.com/juglab/EmbedSeg.git
## cd EmbedSeg
## pip install -e .
